# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MultiUnion
                                 A QGIS plugin
 This plugin runs the UNION tool, allowing you to use up to 6 vector polygon layers simultaneously.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-11
        copyright            : (C) 2023 by Antonio Sobral Almeida
        email                : 66124.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antonio Sobral Almeida'
__date__ = '2023-11-11'
__copyright__ = '(C) 2023 by Antonio Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MultiUnion class from file MultiUnion.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .multi_union import MultiUnionPlugin
    return MultiUnionPlugin()
